### ISSUE TITLE
Read only mode is not working.

### ISSUE THREAD

**Issue by sruinz** [HemmeligOrg/Hemmelig.app#187] opened 2023-05-14 20:13 UTC
### Description
{"error":"Access denied. You are not allowed to create secrets. 🥲"}

When Read-only mode is enabled, not login users can only view the message above.

I cannot see any login screens, secret messages, or settings screens. The only solution is to reset the database.

If I am using Docker on Synology and want to use Read only mode, what additional steps do I need to take?

### Screenshots

![image](https://github.com/HemmeligOrg/Hemmelig.app/assets/63243848/f9f61774-f2f5-44d1-9446-998acf403b42)
![image](https://github.com/HemmeligOrg/Hemmelig.app/assets/63243848/aaacc6eb-81e5-4947-9171-55850b046971)

**Comment by tmischok** [comment] 2023-05-15 07:34
Hi there,
according to the read-only.js file, you have to be signed in to access the website (or sign in via the authentication/account api beforehand?).

I modified the [read-only.js](https://github.com/tmischok/Hemmelig.app/blob/ae5d28a162be0aaaf33c1d82ca0c2e1ed9b9228a/src/server/prehandlers/read-only.js) file inside my fork some time ago so that only the post request to the secret api may be blocked.

Cheers.

**Comment by sruinz** [comment] 2023-05-15 23:27
Thank you.
I hope the issue can be resolved with the modified file, but I'm not sure how to apply the changes.
It seems that there is no separate existing image, so should I create an image myself?
If so, I'll give it a try. Thank you.

**Comment by bjarneo** [comment] 2023-05-16 13:20
Hi. Thanks for your issue. Will look into this as soon as I got some spare time.

**Comment by bjarneo** [comment] 2023-05-21 13:26
Hi, 

I looked into this issue now, and it is suppose to behave like this. If you put the hemmelig instance into read only mode, then you can't sign in users at all. However, you are able to create users that are allowed to access the page which has the state for "creator" or "admin".

Closing as this is not a bug, but a feature. 

We could of course have a discussion if the behaviour should be different. Maybe add a setting that allows users to sign in, but not create secrets.

**Comment by bjarneo** [comment] 2023-05-21 15:57
I think I have to look into this one more time

**Comment by cuneglas** [comment] 2023-09-20 23:09
thanks for your fantastic work, it would be great to have the possibility to open the secret without having to log in or create an account.

**Comment by Almightily** [comment] 2023-11-08 21:48
Please fix this. I want to allow secret creation only for users, but I cannot login if read-only mode enabled

**Comment by bjarneo** [comment] 2023-11-09 06:47
@almightily, PRs can always be opened :)

**Comment by graphixillusion** [comment] 2024-01-09 03:13
>  (or sign in via the authentication/account api beforehand?).

How to signin back as admin user when ready-only mode is on ?

**Comment by bjarneo** [comment] 2024-01-25 20:42
@graphixillusion you should be able to sign in if you set the instance to read only

**Comment by bjarneo** [comment] 2024-01-25 20:45
There is no bug here

1. Read only
This means that you can't create secrets if you are a normal user. This is the intended behavior.

2. Disable user account creation
This will disable user account creation


Not sure what you guys want me to fix as this is working as expected?

**Comment by bjarneo** [comment] 2024-01-25 20:45
@Almightily that is not the intended behavior here

**Comment by sruinz** [comment] 2024-01-25 22:37
> There is no bug here > > 1. Read only > This means that you can't create secrets if you are a normal user. This is the intended behavior. > 2. Disable user account creation > This will disable user account creation > > Not sure what you guys want me to fix as this is working as expected?

> There is no bug here
> 
> 1. Read only
>    This means that you can't create secrets if you are a normal user. This is the intended behavior.
> 2. Disable user account creation
>    This will disable user account creation
> 
> Not sure what you guys want me to fix as this is working as expected?

![SmartSelectImage_2024-01-26-07-26-02](https://github.com/HemmeligOrg/Hemmelig.app/assets/63243848/43f32c29-bd3e-424a-8f55-02b8ba936b0c)

![SmartSelectImage_2024-01-26-07-26-20](https://github.com/HemmeligOrg/Hemmelig.app/assets/63243848/d7cf35cd-907e-4a41-974d-c7eca5e7f298)
(edge inPrivate)

![SmartSelectImage_2024-01-26-07-27-39](https://github.com/HemmeligOrg/Hemmelig.app/assets/63243848/9c1a7f17-3755-4a64-84ab-e6f187dc0146)
(chrome secret mode)

The Disable user account creation feature is not relevant.
If Read only mode is activated, the login window will not appear and only an error message will be displayed when connecting to the specified domain.

When you access the domain using the nomal Edge browser, you can see the secret creation screen and log in, but you cannot log in in the Edge inPrivate window or Chrome Secret mode.

**Comment by graphixillusion** [comment] 2024-01-26 01:04
> @graphixillusion you should be able to sign in if you set the instance to read only

Yep, the behavior is the same as @sruinz described. If read only mode is active you cannot login back because of the error in the screenshot above.

**Comment by bjarneo** [comment] 2024-01-26 07:32
Ah. I finally understand. I never tried this outside of development. That is why I never found this bug. The behavior from dev & prod is a bit different, as in dev you proxy the API. 

Yes, I now can reproduce your issue. Will for sure fix this.

**Comment by bjarneo** [comment] 2024-01-26 07:48
Could you try this version? https://github.com/HemmeligOrg/Hemmelig.app/releases/tag/v5.16.8

Thank you for your patience.

**Comment by sruinz** [comment] 2024-01-26 08:12
> Could you try this version? https://github.com/HemmeligOrg/Hemmelig.app/releases/tag/v5.16.8
> 
> Thank you for your patience.

![image](https://github.com/HemmeligOrg/Hemmelig.app/assets/63243848/cfd344ed-6acb-42cd-b492-6984f4cc387c)

Thank you for your efforts.

Read-only mode works fine.

Now users who are not logged in can only view secrets but cannot create them.

thank you

**Closed** 2024-01-26 08:15 UTC
Labels: bug

**Comment by cuneglas** [comment] 2024-01-26 11:07
It’s working perfectly. 
Thanks for your hard work.
