### ISSUE TITLE
Blank screens for "Secrets" and "Users", even on hemmelig.app

### ISSUE THREAD

**Issue by ltguillaume** [HemmeligOrg/Hemmelig.app#211] opened 2023-09-07 09:20 UTC
### Description

Under [Account], I find the following issues (while self-hosted _and_ on https://hemmelig.app):
1. The [Account] pane just shows a spinner, nothing else.
    > GET https://hemmelig.app/api/account/                [HTTP/2 401 Unauthorized 64ms]
2. Clicking on [Secrets] results in a completely blank page:
    > TypeError: x.map is not a function
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > Jc https://hemmelig.app/assets/index-12b7880e.js:37
    > Nu https://hemmelig.app/assets/index-12b7880e.js:37
    > Sv https://hemmelig.app/assets/index-12b7880e.js:41
    > yv https://hemmelig.app/assets/index-12b7880e.js:41
    > Q_ https://hemmelig.app/assets/index-12b7880e.js:41
    > yo https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > At https://hemmelig.app/assets/index-12b7880e.js:37
    > hr https://hemmelig.app/assets/index-12b7880e.js:39
    > tf https://hemmelig.app/assets/index-12b7880e.js:37
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > rS https://hemmelig.app/assets/index-12b7880e.js:41
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > $r https://hemmelig.app/assets/index-12b7880e.js:41
    > eS https://hemmelig.app/assets/index-12b7880e.js:41
    > Y https://hemmelig.app/assets/index-12b7880e.js:26
    > onmessage https://hemmelig.app/assets/index-12b7880e.js:26

    and

    > Uncaught (in promise) TypeError: x.map is not a function
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > Jc https://hemmelig.app/assets/index-12b7880e.js:37
    > Nu https://hemmelig.app/assets/index-12b7880e.js:37
    > Sv https://hemmelig.app/assets/index-12b7880e.js:41
    > yv https://hemmelig.app/assets/index-12b7880e.js:41
    > Q_ https://hemmelig.app/assets/index-12b7880e.js:41
    > yo https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > At https://hemmelig.app/assets/index-12b7880e.js:37
    > hr https://hemmelig.app/assets/index-12b7880e.js:39
    > tf https://hemmelig.app/assets/index-12b7880e.js:37
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > rS https://hemmelig.app/assets/index-12b7880e.js:41
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > $r https://hemmelig.app/assets/index-12b7880e.js:41
    > eS https://hemmelig.app/assets/index-12b7880e.js:41
    > Y https://hemmelig.app/assets/index-12b7880e.js:26
    > onmessage https://hemmelig.app/assets/index-12b7880e.js:26
    > [index-12b7880e.js:39:73](https://hemmelig.app/assets/index-12b7880e.js)
3. Clicking on [Users] results in a completely blank page:
    > TypeError: r.map is not a function
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > Jc https://hemmelig.app/assets/index-12b7880e.js:37
    > Nu https://hemmelig.app/assets/index-12b7880e.js:37
    > Sv https://hemmelig.app/assets/index-12b7880e.js:41
    > yv https://hemmelig.app/assets/index-12b7880e.js:41
    > Q_ https://hemmelig.app/assets/index-12b7880e.js:41
    > yo https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > At https://hemmelig.app/assets/index-12b7880e.js:37
    > hr https://hemmelig.app/assets/index-12b7880e.js:39
    > tf https://hemmelig.app/assets/index-12b7880e.js:37
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > rS https://hemmelig.app/assets/index-12b7880e.js:41
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > $r https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > Y https://hemmelig.app/assets/index-12b7880e.js:26
    > onmessage https://hemmelig.app/assets/index-12b7880e.js:26
    > EventHandlerNonNull* https://hemmelig.app/assets/index-12b7880e.js:26
    > <anonymous> https://hemmelig.app/assets/index-12b7880e.js:26

    and

    > Uncaught (in promise) TypeError: r.map is not a function
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > Jc https://hemmelig.app/assets/index-12b7880e.js:37
    > Nu https://hemmelig.app/assets/index-12b7880e.js:37
    > Sv https://hemmelig.app/assets/index-12b7880e.js:41
    > yv https://hemmelig.app/assets/index-12b7880e.js:41
    > Q_ https://hemmelig.app/assets/index-12b7880e.js:41
    > yo https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > At https://hemmelig.app/assets/index-12b7880e.js:37
    > hr https://hemmelig.app/assets/index-12b7880e.js:39
    > tf https://hemmelig.app/assets/index-12b7880e.js:37
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > rS https://hemmelig.app/assets/index-12b7880e.js:41
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > $r https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > Y https://hemmelig.app/assets/index-12b7880e.js:26
    > onmessage https://hemmelig.app/assets/index-12b7880e.js:26
    > EventHandlerNonNull* https://hemmelig.app/assets/index-12b7880e.js:26
    > <anonymous> https://hemmelig.app/assets/index-12b7880e.js:26

Additionally, the browser console is riddled with these issues:
> Unexpected value 3.625rem parsing width attribute.                [index-12b7880e.js:33:5143](https://hemmelig.app/assets/index-12b7880e.js)

**Comment by bjarneo** [comment] 2023-09-08 07:14
Hi, thank you for the issue.

Yes, this is known. It is due to the lack of proper authentication check. If you JWT expire there is no refresh of the token which causes this. Also, while visiting the pages behind an auth will then fail because it does not have proper check.


This one I can't reproduce.
> Unexpected value 3.625rem parsing width attribute. [index-12b7880e.js:33:5143](https://hemmelig.app/assets/index-12b7880e.js)

**Comment by ltguillaume** [comment] 2023-09-08 10:21
> Yes, this is known.

Ah ok. I didn''t find an existing issue related to this. Judging from your description, it's not something I can solve myself, so I guess it's good to have this issue open in order to track your progress with regard to the problem,

> This one I can't reproduce.

Seems to be Firefox only.

**Comment by bjarneo** [comment] 2023-09-08 10:38
It was great that you opened the issue. 

> Seems to be Firefox only.

Ah, yes, noticed it. Thank you.

**Comment by m4-droid** [comment] 2023-10-28 14:58
Hi, @bjarneo 
can you assign this issue to me?
I am working on it

**Closed** 2023-10-31 08:11 UTC
Labels: bug, Hacktoberfest
